"""Add phone to user and fix register logic

Revision ID: 89b18b3ad956
Revises: 9297446c656f
Create Date: 2026-04-13 23:35:38.977218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '89b18b3ad956'
down_revision: Union[str, None] = '9297446c656f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    inspector = inspect(op.get_bind())
    if "users" in inspector.get_table_names():
        user_columns = {column["name"]: column for column in inspector.get_columns("users")}
        if "phone" in user_columns:
            return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
