"""mtom

Revision ID: 9297446c656f
Revises: 8b40f2436600
Create Date: 2026-03-21 14:34:37.427952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9297446c656f'
down_revision: Union[str, None] = '8b40f2436600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprises', sa.Column('logo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enterprises', 'logo_url')
    # ### end Alembic commands ###
