"""test detect changes

Revision ID: c7a84a55543d
Revises: fbbcd21c1dec
Create Date: 2026-03-20 19:54:04.848003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7a84a55543d'
down_revision: Union[str, None] = 'fbbcd21c1dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TYPE IF EXISTS documenttype;") 
    op.execute("DROP TYPE IF EXISTS orderstatus;") 
    op.execute("DROP TYPE IF EXISTS paymentstatus;") 
    op.execute("DROP TYPE IF EXISTS userrole;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enterprises', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'enterprises', ['short_name'])
    op.alter_column('users', 'enterprise_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_user_enterprise'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'enterprises', ['enterprise_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_enterprise'), 'users', 'enterprises', ['enterprise_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'enterprise_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'enterprises', type_='unique')
    op.alter_column('enterprises', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
