"""mtom

Revision ID: 8b40f2436600
Revises: c7a84a55543d
Create Date: 2026-03-21 13:49:00.207453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '8b40f2436600'
down_revision: Union[str, None] = 'c7a84a55543d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    inspector = inspect(op.get_bind())
    if "user_enterprises" in inspector.get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_enterprises',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('enterprise_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'enterprise_id')
    )
    op.drop_constraint(op.f('users_enterprise_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'enterprise_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enterprise_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_enterprise_id_fkey'), 'users', 'enterprises', ['enterprise_id'], ['id'], ondelete='SET NULL')
    op.drop_table('user_enterprises')
    # ### end Alembic commands ###
