"""initial schema

Revision ID: 1c020ff9f495
Revises: 
Create Date: 2026-02-19 17:29:46.736251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c020ff9f495'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'user_min',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.Computed('LEAST(user1_id, user2_id)', persisted=True))
    op.alter_column('chats', 'user_max',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.Computed('GREATEST(user1_id, user2_id)', persisted=True))
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('enterprise_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_er_author'), table_name='enterprise_reviews')
    op.drop_index(op.f('idx_er_target'), table_name='enterprise_reviews')
    op.alter_column('enterprises', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_favorites_user'), table_name='favorites')
    op.drop_constraint(op.f('uq_favorite'), 'favorites', type_='unique')
    op.create_index('uq_favorite', 'favorites', ['user_id', 'product_id'], unique=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_messages_chat_created_at'), table_name='messages')
    op.drop_index(op.f('idx_messages_chat_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_sender_id'), table_name='messages')
    op.alter_column('order_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_order_items_order'), table_name='order_items')
    op.drop_index(op.f('idx_order_items_product'), table_name='order_items')
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_orders_buyer'), table_name='orders')
    op.drop_index(op.f('idx_orders_seller'), table_name='orders')
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_payments_order'), table_name='payments')
    op.alter_column('product_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_pr_product'), table_name='product_reviews')
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.drop_index(op.f('idx_products_enterprise'), table_name='products')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_products_enterprise'), 'products', ['enterprise_id'], unique=False)
    op.create_index(op.f('idx_products_category'), 'products', ['category_id'], unique=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_pr_product'), 'product_reviews', ['product_id'], unique=False)
    op.alter_column('product_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_payments_order'), 'payments', ['order_id'], unique=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_orders_seller'), 'orders', ['seller_enterprise_id'], unique=False)
    op.create_index(op.f('idx_orders_buyer'), 'orders', ['buyer_enterprise_id'], unique=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_order_items_product'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('idx_order_items_order'), 'order_items', ['order_id'], unique=False)
    op.alter_column('order_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('idx_messages_chat_created_at'), 'messages', ['chat_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('uq_favorite', table_name='favorites')
    op.create_unique_constraint(op.f('uq_favorite'), 'favorites', ['user_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_favorites_user'), 'favorites', ['user_id'], unique=False)
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('enterprises', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_er_target'), 'enterprise_reviews', ['target_enterprise_id'], unique=False)
    op.create_index(op.f('idx_er_author'), 'enterprise_reviews', ['author_enterprise_id'], unique=False)
    op.alter_column('enterprise_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chats', 'user_max',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.Computed('GREATEST(user1_id, user2_id)', persisted=True))
    op.alter_column('chats', 'user_min',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_server_default=sa.Computed('LEAST(user1_id, user2_id)', persisted=True))
    op.alter_column('carts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
